name: Release XCStringsGen Binary

on:
  push:
    tags: ["*"]

jobs:
  build-release:
    name: Build and Release
    runs-on: macos-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Build Universal Binary
        run: |
          # Build for Apple Silicon (arm64)
          swift build \
            --product XCStringsGen \
            --configuration release \
            --arch arm64 \
            --build-path .build/arm64

          # Build for Intel (x86_64)
          swift build \
            --product XCStringsGen \
            --configuration release \
            --arch x86_64 \
            --build-path .build/x86_64

          # Combine the binaries into a universal binary
          mkdir -p release-artifact
          lipo -create \
            .build/arm64/release/XCStringsGen \
            .build/x86_64/release/XCStringsGen \
            -output release-artifact/XCStringsGen

      - name: Generate info.json
        run: |
          cat <<EOF > release-artifact/info.json
          {
            "schemaVersion": "1.0",
            "artifacts": {
              "XCStringsGen": {
                "version": "${{ github.ref_name }}",
                "type": "executable",
                "variants": [
                  {
                    "path": "XCStringsGen",
                    "supportedTriples": [
                      "x86_64-apple-macosx",
                      "arm64-apple-macosx"
                    ]
                  }
                ]
              }
            }
          }
          EOF

      - name: Package Release Artifact with Checksum
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cp LICENSE release-artifact/
          cd release-artifact
          zip XCStringsGen.zip XCStringsGen info.json LICENSE
          
          checksum=$(shasum -a 256 XCStringsGen.zip | awk '{ print $1 }')
          gh release edit ${{ github.ref_name }} --notes "Checksum for XCStringsGen.zip: \`$checksum\`"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: release-artifact/XCStringsGen.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
